"""empty message

Revision ID: 207084f36c90
Revises: 0f89dc40acf7
Create Date: 2019-11-30 21:38:52.645854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '207084f36c90'
down_revision = '0f89dc40acf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
